apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-docker-example
  template:
    metadata:
      labels:
        app: java-docker-example
    spec:
      containers:
        - name: java-app
          image: 980637429038.dkr.ecr.ap-south-1.amazonaws.com/demo-app:latest
          ports:
            - containerPort: 8081
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: java-docker-service
spec:
  selector:
    app: java-docker-example
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081