name: CI for image and push to AWS ECR

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: docker build -t demo-app ./java-docker-example

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag the Docker image
        run: docker tag demo-app 980637429038.dkr.ecr.ap-south-1.amazonaws.com/demo-app:tarun.0.${{ github.run_number }}

      - name: Push Docker image to AWS ECR
        run: docker push 980637429038.dkr.ecr.ap-south-1.amazonaws.com/demo-app:tarun.0.${{ github.run_number }}
